package kr.nerv.antop.entity.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AttachExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public AttachExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSeqIsNull() {
			addCriterion("seq is null");
			return (Criteria) this;
		}

		public Criteria andSeqIsNotNull() {
			addCriterion("seq is not null");
			return (Criteria) this;
		}

		public Criteria andSeqEqualTo(Integer value) {
			addCriterion("seq =", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotEqualTo(Integer value) {
			addCriterion("seq <>", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThan(Integer value) {
			addCriterion("seq >", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
			addCriterion("seq >=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThan(Integer value) {
			addCriterion("seq <", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThanOrEqualTo(Integer value) {
			addCriterion("seq <=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqIn(List<Integer> values) {
			addCriterion("seq in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotIn(List<Integer> values) {
			addCriterion("seq not in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqBetween(Integer value1, Integer value2) {
			addCriterion("seq between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotBetween(Integer value1, Integer value2) {
			addCriterion("seq not between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andPathIsNull() {
			addCriterion("path is null");
			return (Criteria) this;
		}

		public Criteria andPathIsNotNull() {
			addCriterion("path is not null");
			return (Criteria) this;
		}

		public Criteria andPathEqualTo(String value) {
			addCriterion("path =", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathNotEqualTo(String value) {
			addCriterion("path <>", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathGreaterThan(String value) {
			addCriterion("path >", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathGreaterThanOrEqualTo(String value) {
			addCriterion("path >=", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathLessThan(String value) {
			addCriterion("path <", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathLessThanOrEqualTo(String value) {
			addCriterion("path <=", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathLike(String value) {
			addCriterion("path like", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathNotLike(String value) {
			addCriterion("path not like", value, "path");
			return (Criteria) this;
		}

		public Criteria andPathIn(List<String> values) {
			addCriterion("path in", values, "path");
			return (Criteria) this;
		}

		public Criteria andPathNotIn(List<String> values) {
			addCriterion("path not in", values, "path");
			return (Criteria) this;
		}

		public Criteria andPathBetween(String value1, String value2) {
			addCriterion("path between", value1, value2, "path");
			return (Criteria) this;
		}

		public Criteria andPathNotBetween(String value1, String value2) {
			addCriterion("path not between", value1, value2, "path");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNull() {
			addCriterion("file_name is null");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNotNull() {
			addCriterion("file_name is not null");
			return (Criteria) this;
		}

		public Criteria andFileNameEqualTo(String value) {
			addCriterion("file_name =", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotEqualTo(String value) {
			addCriterion("file_name <>", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThan(String value) {
			addCriterion("file_name >", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThanOrEqualTo(String value) {
			addCriterion("file_name >=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThan(String value) {
			addCriterion("file_name <", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThanOrEqualTo(String value) {
			addCriterion("file_name <=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLike(String value) {
			addCriterion("file_name like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotLike(String value) {
			addCriterion("file_name not like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameIn(List<String> values) {
			addCriterion("file_name in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotIn(List<String> values) {
			addCriterion("file_name not in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameBetween(String value1, String value2) {
			addCriterion("file_name between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotBetween(String value1, String value2) {
			addCriterion("file_name not between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andRealNameIsNull() {
			addCriterion("real_name is null");
			return (Criteria) this;
		}

		public Criteria andRealNameIsNotNull() {
			addCriterion("real_name is not null");
			return (Criteria) this;
		}

		public Criteria andRealNameEqualTo(String value) {
			addCriterion("real_name =", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotEqualTo(String value) {
			addCriterion("real_name <>", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameGreaterThan(String value) {
			addCriterion("real_name >", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameGreaterThanOrEqualTo(String value) {
			addCriterion("real_name >=", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameLessThan(String value) {
			addCriterion("real_name <", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameLessThanOrEqualTo(String value) {
			addCriterion("real_name <=", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameLike(String value) {
			addCriterion("real_name like", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotLike(String value) {
			addCriterion("real_name not like", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameIn(List<String> values) {
			addCriterion("real_name in", values, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotIn(List<String> values) {
			addCriterion("real_name not in", values, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameBetween(String value1, String value2) {
			addCriterion("real_name between", value1, value2, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotBetween(String value1, String value2) {
			addCriterion("real_name not between", value1, value2, "realName");
			return (Criteria) this;
		}

		public Criteria andContextTypeIsNull() {
			addCriterion("context_type is null");
			return (Criteria) this;
		}

		public Criteria andContextTypeIsNotNull() {
			addCriterion("context_type is not null");
			return (Criteria) this;
		}

		public Criteria andContextTypeEqualTo(String value) {
			addCriterion("context_type =", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeNotEqualTo(String value) {
			addCriterion("context_type <>", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeGreaterThan(String value) {
			addCriterion("context_type >", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeGreaterThanOrEqualTo(String value) {
			addCriterion("context_type >=", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeLessThan(String value) {
			addCriterion("context_type <", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeLessThanOrEqualTo(String value) {
			addCriterion("context_type <=", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeLike(String value) {
			addCriterion("context_type like", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeNotLike(String value) {
			addCriterion("context_type not like", value, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeIn(List<String> values) {
			addCriterion("context_type in", values, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeNotIn(List<String> values) {
			addCriterion("context_type not in", values, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeBetween(String value1, String value2) {
			addCriterion("context_type between", value1, value2, "contextType");
			return (Criteria) this;
		}

		public Criteria andContextTypeNotBetween(String value1, String value2) {
			addCriterion("context_type not between", value1, value2, "contextType");
			return (Criteria) this;
		}

		public Criteria andExtIsNull() {
			addCriterion("ext is null");
			return (Criteria) this;
		}

		public Criteria andExtIsNotNull() {
			addCriterion("ext is not null");
			return (Criteria) this;
		}

		public Criteria andExtEqualTo(String value) {
			addCriterion("ext =", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtNotEqualTo(String value) {
			addCriterion("ext <>", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtGreaterThan(String value) {
			addCriterion("ext >", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtGreaterThanOrEqualTo(String value) {
			addCriterion("ext >=", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtLessThan(String value) {
			addCriterion("ext <", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtLessThanOrEqualTo(String value) {
			addCriterion("ext <=", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtLike(String value) {
			addCriterion("ext like", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtNotLike(String value) {
			addCriterion("ext not like", value, "ext");
			return (Criteria) this;
		}

		public Criteria andExtIn(List<String> values) {
			addCriterion("ext in", values, "ext");
			return (Criteria) this;
		}

		public Criteria andExtNotIn(List<String> values) {
			addCriterion("ext not in", values, "ext");
			return (Criteria) this;
		}

		public Criteria andExtBetween(String value1, String value2) {
			addCriterion("ext between", value1, value2, "ext");
			return (Criteria) this;
		}

		public Criteria andExtNotBetween(String value1, String value2) {
			addCriterion("ext not between", value1, value2, "ext");
			return (Criteria) this;
		}

		public Criteria andFileSizeIsNull() {
			addCriterion("file_size is null");
			return (Criteria) this;
		}

		public Criteria andFileSizeIsNotNull() {
			addCriterion("file_size is not null");
			return (Criteria) this;
		}

		public Criteria andFileSizeEqualTo(Integer value) {
			addCriterion("file_size =", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeNotEqualTo(Integer value) {
			addCriterion("file_size <>", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeGreaterThan(Integer value) {
			addCriterion("file_size >", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeGreaterThanOrEqualTo(Integer value) {
			addCriterion("file_size >=", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeLessThan(Integer value) {
			addCriterion("file_size <", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeLessThanOrEqualTo(Integer value) {
			addCriterion("file_size <=", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeIn(List<Integer> values) {
			addCriterion("file_size in", values, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeNotIn(List<Integer> values) {
			addCriterion("file_size not in", values, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeBetween(Integer value1, Integer value2) {
			addCriterion("file_size between", value1, value2, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeNotBetween(Integer value1, Integer value2) {
			addCriterion("file_size not between", value1, value2, "fileSize");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNull() {
			addCriterion("add_date is null");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNotNull() {
			addCriterion("add_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedEqualTo(Date value) {
			addCriterion("add_date =", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotEqualTo(Date value) {
			addCriterion("add_date <>", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThan(Date value) {
			addCriterion("add_date >", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("add_date >=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThan(Date value) {
			addCriterion("add_date <", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThanOrEqualTo(Date value) {
			addCriterion("add_date <=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedIn(List<Date> values) {
			addCriterion("add_date in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotIn(List<Date> values) {
			addCriterion("add_date not in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedBetween(Date value1, Date value2) {
			addCriterion("add_date between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotBetween(Date value1, Date value2) {
			addCriterion("add_date not between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andBoardIdIsNull() {
			addCriterion("board_id is null");
			return (Criteria) this;
		}

		public Criteria andBoardIdIsNotNull() {
			addCriterion("board_id is not null");
			return (Criteria) this;
		}

		public Criteria andBoardIdEqualTo(Integer value) {
			addCriterion("board_id =", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdNotEqualTo(Integer value) {
			addCriterion("board_id <>", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdGreaterThan(Integer value) {
			addCriterion("board_id >", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("board_id >=", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdLessThan(Integer value) {
			addCriterion("board_id <", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdLessThanOrEqualTo(Integer value) {
			addCriterion("board_id <=", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdIn(List<Integer> values) {
			addCriterion("board_id in", values, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdNotIn(List<Integer> values) {
			addCriterion("board_id not in", values, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdBetween(Integer value1, Integer value2) {
			addCriterion("board_id between", value1, value2, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdNotBetween(Integer value1, Integer value2) {
			addCriterion("board_id not between", value1, value2, "boardId");
			return (Criteria) this;
		}

		public Criteria andSessionIsNull() {
			addCriterion("session_id is null");
			return (Criteria) this;
		}

		public Criteria andSessionIsNotNull() {
			addCriterion("session_id is not null");
			return (Criteria) this;
		}

		public Criteria andSessionEqualTo(String value) {
			addCriterion("session_id =", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionNotEqualTo(String value) {
			addCriterion("session_id <>", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionGreaterThan(String value) {
			addCriterion("session_id >", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionGreaterThanOrEqualTo(String value) {
			addCriterion("session_id >=", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionLessThan(String value) {
			addCriterion("session_id <", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionLessThanOrEqualTo(String value) {
			addCriterion("session_id <=", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionLike(String value) {
			addCriterion("session_id like", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionNotLike(String value) {
			addCriterion("session_id not like", value, "session");
			return (Criteria) this;
		}

		public Criteria andSessionIn(List<String> values) {
			addCriterion("session_id in", values, "session");
			return (Criteria) this;
		}

		public Criteria andSessionNotIn(List<String> values) {
			addCriterion("session_id not in", values, "session");
			return (Criteria) this;
		}

		public Criteria andSessionBetween(String value1, String value2) {
			addCriterion("session_id between", value1, value2, "session");
			return (Criteria) this;
		}

		public Criteria andSessionNotBetween(String value1, String value2) {
			addCriterion("session_id not between", value1, value2, "session");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Boolean value) {
			addCriterion("del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Boolean value) {
			addCriterion("del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Boolean value) {
			addCriterion("del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Boolean value) {
			addCriterion("del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Boolean> values) {
			addCriterion("del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Boolean> values) {
			addCriterion("del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ab_board_file
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 11 09:37:06 KST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}