package kr.nerv.antop.entity.model;

import java.util.Date;

public class Attach {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.seq
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private Integer seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.path
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.file_name
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.real_name
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.context_type
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private String contextType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.ext
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private String ext;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.file_size
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private Integer fileSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.add_date
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.board_id
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private Integer boardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.session_id
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private String session;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ab_board_file.del_flag
	 * 
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	private Boolean delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.seq
	 * 
	 * @return the value of ab_board_file.seq
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.seq
	 * 
	 * @param seq
	 *            the value for ab_board_file.seq
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.path
	 * 
	 * @return the value of ab_board_file.path
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.path
	 * 
	 * @param path
	 *            the value for ab_board_file.path
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.file_name
	 * 
	 * @return the value of ab_board_file.file_name
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.file_name
	 * 
	 * @param fileName
	 *            the value for ab_board_file.file_name
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.real_name
	 * 
	 * @return the value of ab_board_file.real_name
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.real_name
	 * 
	 * @param realName
	 *            the value for ab_board_file.real_name
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.context_type
	 * 
	 * @return the value of ab_board_file.context_type
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public String getContextType() {
		return contextType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.context_type
	 * 
	 * @param contextType
	 *            the value for ab_board_file.context_type
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setContextType(String contextType) {
		this.contextType = contextType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.ext
	 * 
	 * @return the value of ab_board_file.ext
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public String getExt() {
		return ext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.ext
	 * 
	 * @param ext
	 *            the value for ab_board_file.ext
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setExt(String ext) {
		this.ext = ext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.file_size
	 * 
	 * @return the value of ab_board_file.file_size
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public Integer getFileSize() {
		return fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.file_size
	 * 
	 * @param fileSize
	 *            the value for ab_board_file.file_size
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.add_date
	 * 
	 * @return the value of ab_board_file.add_date
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.add_date
	 * 
	 * @param created
	 *            the value for ab_board_file.add_date
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.board_id
	 * 
	 * @return the value of ab_board_file.board_id
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public Integer getBoardId() {
		return boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.board_id
	 * 
	 * @param boardId
	 *            the value for ab_board_file.board_id
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.session_id
	 * 
	 * @return the value of ab_board_file.session_id
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public String getSession() {
		return session;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.session_id
	 * 
	 * @param session
	 *            the value for ab_board_file.session_id
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setSession(String session) {
		this.session = session;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ab_board_file.del_flag
	 * 
	 * @return the value of ab_board_file.del_flag
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public Boolean getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ab_board_file.del_flag
	 * 
	 * @param delFlag
	 *            the value for ab_board_file.del_flag
	 * @mbggenerated Mon Jul 18 22:37:07 KST 2011
	 */
	public void setDelFlag(Boolean delFlag) {
		this.delFlag = delFlag;
	}

}