package kr.nerv.antop.entity.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab_board_comment.comment_id
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab_board_comment.author
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab_board_comment.pwd
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab_board_comment.write_date
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab_board_comment.modify_date
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab_board_comment.board_id
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    private Integer boardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab_board_comment.content
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab_board_comment.comment_id
     *
     * @return the value of ab_board_comment.comment_id
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab_board_comment.comment_id
     *
     * @param commentId the value for ab_board_comment.comment_id
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab_board_comment.author
     *
     * @return the value of ab_board_comment.author
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab_board_comment.author
     *
     * @param author the value for ab_board_comment.author
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab_board_comment.pwd
     *
     * @return the value of ab_board_comment.pwd
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab_board_comment.pwd
     *
     * @param pwd the value for ab_board_comment.pwd
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab_board_comment.write_date
     *
     * @return the value of ab_board_comment.write_date
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab_board_comment.write_date
     *
     * @param created the value for ab_board_comment.write_date
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab_board_comment.modify_date
     *
     * @return the value of ab_board_comment.modify_date
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab_board_comment.modify_date
     *
     * @param modified the value for ab_board_comment.modify_date
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab_board_comment.board_id
     *
     * @return the value of ab_board_comment.board_id
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab_board_comment.board_id
     *
     * @param boardId the value for ab_board_comment.board_id
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab_board_comment.content
     *
     * @return the value of ab_board_comment.content
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab_board_comment.content
     *
     * @param content the value for ab_board_comment.content
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    public void setContent(String content) {
        this.content = content;
    }
}