package kr.nerv.antop.entity.mapper;

import java.util.List;
import kr.nerv.antop.entity.model.Attach;
import kr.nerv.antop.entity.model.AttachExample;
import org.apache.ibatis.annotations.Param;

public interface AttachMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int countByExample(AttachExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int deleteByExample(AttachExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int deleteByPrimaryKey(Integer seq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int insert(Attach record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int insertSelective(Attach record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	List<Attach> selectByExample(AttachExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	Attach selectByPrimaryKey(Integer seq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int updateByExampleSelective(@Param("record") Attach record, @Param("example") AttachExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int updateByExample(@Param("record") Attach record, @Param("example") AttachExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int updateByPrimaryKeySelective(Attach record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ab_board_file
	 * @mbggenerated  Mon Jul 18 22:37:07 KST 2011
	 */
	int updateByPrimaryKey(Attach record);
}