package kr.nerv.antop.entity.mapper;

import java.util.List;
import kr.nerv.antop.entity.model.Board;
import kr.nerv.antop.entity.model.BoardExample;
import org.apache.ibatis.annotations.Param;

public interface BoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int countByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int deleteByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int deleteByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int insertSelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    List<Board> selectByExampleWithBLOBs(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    List<Board> selectByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    Board selectByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByExampleSelective(@Param("record") Board record, @Param("example") BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") Board record, @Param("example") BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByExample(@Param("record") Board record, @Param("example") BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByPrimaryKeySelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByPrimaryKeyWithBLOBs(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByPrimaryKey(Board record);
    
    double minThread();
}