package kr.nerv.antop.entity.mapper;

import java.util.List;
import kr.nerv.antop.entity.model.Comment;
import kr.nerv.antop.entity.model.CommentExample;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    List<Comment> selectByExampleWithBLOBs(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    Comment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByPrimaryKeyWithBLOBs(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab_board_comment
     *
     * @mbggenerated Mon Jul 11 09:37:06 KST 2011
     */
    int updateByPrimaryKey(Comment record);
}